upgrade/iOSnDroid-MvvmCross7
* Migrated to AndroidX by Right clicking on the Android project and selecting "Migrate to AndroidX"
* Then updated all the nuget packages by right click on the Packages folder in the Solution explorer-> Update
* Upon building, it told me I was missing another Nuget package Xamarin.AndroidX.Legacy.Support.V4 and Xamarin.AndroidX.Browser, so I added those two as well
* The latest version of the Lottie package doesnt support a target framework less than Android 10, so I had to increase the target framework of the Android project

**Testing**
----------
* Tested on an Android 10 device and the Forms app built
* Tested on iPhone 8 simulator and it worked

**Notes**
----
* Tried to update the Traditional/Native Android project as well, but I got this error "Views/PersonView.cs(55,50,55,61): error CS7069: Reference to type 'MvxColor' claims it is defined in 'MvvmCross', but it could not be found"
* Also had issues updating the TipCalc sample
* Did not test UWP